### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by AzorianMatt** [AzorianSolutions/reflective#6]
### Reflective version

0.1.0

### Steps to Reproduce

Install Reflective into a Python 3.8 environment and attempt to instantiate the class.

### Expected Behavior

The class instantiates as expected.

### Observed Behavior

An exception occurs when running the code:

```
Traceback (most recent call last):
  File "./pg.py", line 3, in <module>
    from reflective.core import Reflective
  File "/home/matt/Projects/as/libs/reflective/src/reflective/__init__.py", line 1, in <module>
    from reflective.core import Reflective
  File "/home/matt/Projects/as/libs/reflective/src/reflective/core.py", line 69, in <module>
    class RCore:
  File "/home/matt/Projects/as/libs/reflective/src/reflective/core.py", line 267, in RCore
    def extract(self, value: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```

**Comment by AzorianMatt** [comment]
Fixed by #7
